"""Add was_auto_assigned to Schedule

Revision ID: 1a55bc627fab
Revises: 80402709ea5c
Create Date: 2025-07-01 12:46:36.744944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a55bc627fab'
down_revision = '80402709ea5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('was_auto_assigned', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reassignment_request', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reassignment_reason', sa.String(length=300), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('meal_preference',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.create_unique_constraint('_user_date_uc', ['user_id', 'date'])
        batch_op.create_index(batch_op.f('ix_schedule_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_user_id'))
        batch_op.drop_constraint('_user_date_uc', type_='unique')
        batch_op.alter_column('meal_preference',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('reassignment_reason')
        batch_op.drop_column('reassignment_request')
        batch_op.drop_column('was_auto_assigned')

    # ### end Alembic commands ###
