"""Add WeekConfig model for week locking functionality

Revision ID: 4fa712f4029f
Revises: f942162f098f
Create Date: 2025-07-02 00:44:57.684282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa712f4029f'
down_revision = 'f942162f098f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('week_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_week_config_week_start_date'), ['week_start_date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('week_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_week_config_week_start_date'))

    op.drop_table('week_config')
    # ### end Alembic commands ###
